### ISSUE TITLE
Better(Pretty) UI

### ISSUE THREAD

**Issue by sheedo** [sheedo/med_appoint_transcriber#5]
Make the UI "sexy", add registration page and login page,

registration - Doctor ID, Doctor email, password

**Comment by sheedo** [comment]
and email and password for login

**Comment by epilk** [comment]
Do we need persistent Doctor ID? Can't the doctor just input patient's email and talk?

**Comment by sheedo** [comment]
yeah @epilk , we can do that, we were only going to add the doctor id because we wanted a reg page
